export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS'
export const RECEIVE_ALL_PROJECTS = 'RECEIVE_ALL_PROJECTS'

export const GET_ONE_PROJECT = 'GET_ONE_PROJECT'
export const RECEIVE_ONE_PROJECT = 'RECEIVE_ONE_PROJECT'

