projects:
  database:
    schemaPath: generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: javascript
          output:
            binding: generated/prisma-schema.js
  app:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
