export const GET_ALL_IMAGES = 'GET_ALL_IMAGES'
export const RECEIVE_ALL_IMAGES = 'RECEIVE_ALL_IMAGES'

export const GET_ONE_IMAGE = 'GET_ONE_IMAGE'
export const RECEIVE_ONE_IMAGE = 'RECEIVE_ONE_IMAGE'

