export const SUBMIT_NEW_PROJECT_DATA = 'SUBMIT_NEW_PROJECT_DATA'
export const SUCCEED_SUBMITTING_NEW_PROJECT_DATA = 'SUCCEED_SUBMITTING_NEW_PROJECT_DATA'
export const FAIL_SUBMITTING_NEW_PROJECT_DATA = 'FAIL_SUBMITTING_NEW_PROJECT_DATA'

export const CLEAR_NEW_PROJECT_FORM = 'CLEAR_NEW_PROJECT_FORM'
export const FINISH_CLEAR_NEW_PROJECT_FORM = 'FINISH_CLEAR_NEW_PROJECT_FORM'

