# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 674f34fa569ca6bc011afb148462a049ec10de15ec9f12c3e2f6dfcc09fef393c299b12135c92a83256aa393af1424c7cd42db135fc4f99dbc3ac0f3cfc6fb3c

test:
  secret_key_base: 59bc1ebef4f71a3eec8b9305707b335ec56620ece7624e99ab3c4ecdf766b69ec5037ea1ac726d0b92e0dd9fb3f38eb78e1fd5c10087ea20504ceb41b3db64ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
